"""Domain models, schemas, and feature contracts for Veya Luma Recommendation Engine Foundation (Step 18).

Provides strictly typed dataclasses and Pydantic models for candidate representation,
user taste profiles, the future ranking model feature contract, and structured explanations.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Set
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class CandidateChannel(str, Enum):
    """Explicit retrieval channel sources for candidate generation."""

    CONTENT_MATCH = "CONTENT_MATCH"
    PREFERENCE_MATCH = "PREFERENCE_MATCH"
    BEHAVIOR_MATCH = "BEHAVIOR_MATCH"
    DISCOVERY = "DISCOVERY"
    COLD_START = "COLD_START"


class ExplanationReasonCode(str, Enum):
    """Structured deterministic explanation codes grounded in catalog evidence."""

    GENRE_ALIGNMENT = "GENRE_ALIGNMENT"
    THEME_RESONANCE = "THEME_RESONANCE"
    MOOD_ALIGNMENT = "MOOD_ALIGNMENT"
    STYLE_ALIGNMENT = "STYLE_ALIGNMENT"
    DIRECTOR_AFFINITY = "DIRECTOR_AFFINITY"
    CAST_AFFINITY = "CAST_AFFINITY"
    PREFERENCE_MATCH = "PREFERENCE_MATCH"
    BEHAVIORAL_RESONANCE = "BEHAVIORAL_RESONANCE"
    GLOBAL_DISCOVERY = "GLOBAL_DISCOVERY"
    UNDISCOVERED_GEM = "UNDISCOVERED_GEM"
    COLD_START_CURATION = "COLD_START_CURATION"
    CROSS_LANGUAGE_DISCOVERY = "CROSS_LANGUAGE_DISCOVERY"


class RecommendationExplanation(BaseModel):
    """Structured deterministic explanation for a recommended movie."""

    model_config = ConfigDict(frozen=True)

    reason_code: str = Field(
        ...,
        description="Standardized machine-readable explanation category code",
    )
    label: str = Field(
        ...,
        description="Human-readable explanation statement grounded in factual evidence",
    )
    evidence: List[str] = Field(
        default_factory=list,
        description="Concrete contributing evidence items (e.g. genre names, themes, director)",
    )


@dataclass(frozen=True)
class CandidateFeatureContract:
    """Stable internal feature contract for candidate evaluation and future ML ranker ingestion.

    Guarantees that every candidate movie exposes normalized signals derived exclusively
    from real canonical catalog metadata and user taste telemetry.
    """

    candidate_id: UUID
    user_id: Optional[UUID]
    source_channel: str
    contributing_channels: List[str]

    # Channel-specific component scores [0.0, 1.0]
    content_score: float
    preference_score: float
    behavior_score: float
    discovery_score: float

    # Multi-axis overlap metrics [0.0, 1.0]
    genre_overlap: float
    theme_overlap: float
    mood_overlap: float
    style_overlap: float
    keyword_overlap: float

    # Entity & context match metrics [0.0, 1.0]
    language_match: float
    director_match: float
    cast_match: float
    era_match: float

    # Catalog & exploration signals [0.0, 1.0]
    novelty_signal: float
    popularity_signal: float
    vote_quality_signal: float

    # Temporal taste alignment [0.0, 1.0]
    recent_taste_alignment: float
    long_term_taste_alignment: float

    def to_dict(self) -> Dict[str, Any]:
        """Serializes feature contract into a dictionary for downstream ML features or logging."""
        return {
            "candidate_id": str(self.candidate_id),
            "user_id": str(self.user_id) if self.user_id else None,
            "source_channel": self.source_channel,
            "contributing_channels": list(self.contributing_channels),
            "content_score": round(self.content_score, 4),
            "preference_score": round(self.preference_score, 4),
            "behavior_score": round(self.behavior_score, 4),
            "discovery_score": round(self.discovery_score, 4),
            "genre_overlap": round(self.genre_overlap, 4),
            "theme_overlap": round(self.theme_overlap, 4),
            "mood_overlap": round(self.mood_overlap, 4),
            "style_overlap": round(self.style_overlap, 4),
            "keyword_overlap": round(self.keyword_overlap, 4),
            "language_match": round(self.language_match, 4),
            "director_match": round(self.director_match, 4),
            "cast_match": round(self.cast_match, 4),
            "era_match": round(self.era_match, 4),
            "novelty_signal": round(self.novelty_signal, 4),
            "popularity_signal": round(self.popularity_signal, 4),
            "vote_quality_signal": round(self.vote_quality_signal, 4),
            "recent_taste_alignment": round(self.recent_taste_alignment, 4),
            "long_term_taste_alignment": round(self.long_term_taste_alignment, 4),
        }


@dataclass
class MovieCandidate:
    """Internal candidate representation generated by a specific channel."""

    movie_id: UUID
    title: str
    original_language: str
    release_year: Optional[int]
    runtime_minutes: Optional[int]
    poster_path: Optional[str]
    backdrop_path: Optional[str]
    popularity: Optional[float]
    vote_average: Optional[float]
    vote_count: Optional[int]

    # Retrieval channel attribution
    primary_channel: str
    contributing_channels: List[str] = field(default_factory=list)
    raw_score: float = 0.0
    final_score: float = 0.0

    # Evidence & features
    features: Optional[CandidateFeatureContract] = None
    explanations: List[RecommendationExplanation] = field(default_factory=list)
    matched_features: Dict[str, List[str]] = field(default_factory=dict)
    is_in_watchlist: bool = False


@dataclass
class UserTasteProfile:
    """Deterministic representation of a user's multi-layered taste signals."""

    user_id: Optional[UUID]
    session_id: Optional[UUID]
    is_cold_start: bool = True

    # Long-term taste signals (historical ratings, favourites, long-term preferences)
    long_term_genres: Dict[str, float] = field(default_factory=dict)
    long_term_themes: Dict[str, float] = field(default_factory=dict)
    long_term_moods: Dict[str, float] = field(default_factory=dict)
    long_term_styles: Dict[str, float] = field(default_factory=dict)
    long_term_languages: Dict[str, float] = field(default_factory=dict)
    long_term_directors: Dict[str, float] = field(default_factory=dict)
    long_term_keywords: Dict[str, float] = field(default_factory=dict)

    # Recent taste signals (recent detail views, clicks, recent ratings)
    recent_genres: Dict[str, float] = field(default_factory=dict)
    recent_themes: Dict[str, float] = field(default_factory=dict)
    recent_moods: Dict[str, float] = field(default_factory=dict)
    recent_styles: Dict[str, float] = field(default_factory=dict)
    recent_languages: Dict[str, float] = field(default_factory=dict)
    recent_directors: Dict[str, float] = field(default_factory=dict)
    recent_keywords: Dict[str, float] = field(default_factory=dict)

    # Explicit user preferences (taxonomy node key -> affinity [-1.0, 1.0])
    explicit_preferences: Dict[str, float] = field(default_factory=dict)

    # Aversion / Negative taste evidence (taxonomies with strong negative evidence)
    negative_taxonomies: Set[str] = field(default_factory=set)

    # Suppression and presentation sets
    seen_movie_ids: Set[UUID] = field(default_factory=set)
    watchlist_movie_ids: Set[UUID] = field(default_factory=set)

    # Combined blended affinities (weighted blend of long_term + recent + explicit)
    combined_genre_affinity: Dict[str, float] = field(default_factory=dict)
    combined_theme_affinity: Dict[str, float] = field(default_factory=dict)
    combined_mood_affinity: Dict[str, float] = field(default_factory=dict)
    combined_style_affinity: Dict[str, float] = field(default_factory=dict)
    combined_language_affinity: Dict[str, float] = field(default_factory=dict)
    combined_director_affinity: Dict[str, float] = field(default_factory=dict)


# API Request & Response Schemas


class RecommendationItemResponse(BaseModel):
    """External API response schema for a single recommended movie."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID = Field(..., description="Canonical movie UUID")
    title: str = Field(..., description="Canonical movie title")
    original_language: str = Field(..., description="ISO 639-1 language code")
    release_year: Optional[int] = Field(None, description="Release year")
    runtime_minutes: Optional[int] = Field(None, description="Runtime in minutes")
    poster_path: Optional[str] = Field(None, description="Poster path")
    backdrop_path: Optional[str] = Field(None, description="Backdrop path")
    popularity: Optional[float] = Field(None, description="Catalog popularity score")
    vote_average: Optional[float] = Field(
        None, description="Catalog vote average rating"
    )
    vote_count: Optional[int] = Field(None, description="Catalog vote count")
    director: Optional[str] = Field(None, description="Principal director name")

    # Recommendation provenance & scoring
    channel: str = Field(..., description="Primary recommendation channel")
    contributing_channels: List[str] = Field(
        default_factory=list,
        description="All channels that generated this candidate",
    )
    score: float = Field(
        ..., description="Deterministic recommendation score [0.0, 1.0]"
    )
    is_in_watchlist: bool = Field(
        False,
        description="True if already in user or guest watchlist",
    )

    # Explainability & feature transparency
    explanations: List[RecommendationExplanation] = Field(
        default_factory=list,
        description="Structured explainability reasons with catalog evidence",
    )
    matched_features: Dict[str, List[str]] = Field(
        default_factory=dict,
        description="Catalog features that matched user taste profile",
    )
    features: Optional[Dict[str, Any]] = Field(
        None,
        description="Internal feature contract metrics (exposed for explainability/audit)",
    )


class RecommendationResponse(BaseModel):
    """Top-level recommendation collection response payload."""

    model_config = ConfigDict(from_attributes=True)

    items: List[RecommendationItemResponse] = Field(
        ...,
        description="Ranked candidate recommendations",
    )
    total_candidates: int = Field(
        ...,
        description="Total candidates retrieved before deduplication and filtering",
    )
    returned_count: int = Field(
        ...,
        description="Number of recommendations returned in this response",
    )
    is_cold_start: bool = Field(
        ...,
        description="True if cold-start curation was applied due to sparse/empty profile",
    )
    channels_represented: List[str] = Field(
        default_factory=list,
        description="List of candidate channels represented in the final slate",
    )
    execution_time_ms: float = Field(
        ...,
        description="Engine execution latency in milliseconds",
    )
