"""create_taste_and_feedback_persistence_tables

Revision ID: 54cc21608f55
Revises: a63771906ea8
Create Date: 2026-10-03 20:51:30.550566

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '54cc21608f55'
down_revision: Union[str, None] = 'a63771906ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True, comment='Owner authenticated user ID, or NULL for guest session'),
    sa.Column('session_id', sa.Uuid(), nullable=True, comment='Owner guest session ID'),
    sa.Column('movie_id', sa.Uuid(), nullable=False, comment='Canonical movie identity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('user_id IS NOT NULL OR session_id IS NOT NULL', name='chk_favourite_owner'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['user_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_favourite_session_created', 'favourite', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_favourite_user_created', 'favourite', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_favourite_movie_id'), 'favourite', ['movie_id'], unique=False)
    op.create_index(op.f('ix_favourite_session_id'), 'favourite', ['session_id'], unique=False)
    op.create_index(op.f('ix_favourite_user_id'), 'favourite', ['user_id'], unique=False)
    op.create_index('uq_favourite_session_movie', 'favourite', ['session_id', 'movie_id'], unique=True, postgresql_where=sa.text('session_id IS NOT NULL'))
    op.create_index('uq_favourite_user_movie', 'favourite', ['user_id', 'movie_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('movie_rating',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Rating author (authenticated user)'),
    sa.Column('movie_id', sa.Uuid(), nullable=False, comment='Target canonical movie identity'),
    sa.Column('rating', sa.Float(), nullable=False, comment='Quantitative evaluation bounded between 1.0 and 10.0'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1.0 AND rating <= 10.0', name='chk_movie_rating_bounds'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_movie_rating_user_movie')
    )
    op.create_index('idx_movie_rating_movie_rating', 'movie_rating', ['movie_id', 'rating'], unique=False)
    op.create_index(op.f('ix_movie_rating_movie_id'), 'movie_rating', ['movie_id'], unique=False)
    op.create_index(op.f('ix_movie_rating_user_id'), 'movie_rating', ['user_id'], unique=False)
    op.create_table('user_movie_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True, comment='Associated authenticated user ID, or NULL for anonymous guest interactions'),
    sa.Column('session_id', sa.Uuid(), nullable=True, comment='Associated user or guest session ID from Step 16'),
    sa.Column('movie_id', sa.Uuid(), nullable=False, comment='Target canonical movie identity'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment="Behavioral signal type: 'impression', 'detail_view', 'click', 'rating'"),
    sa.Column('event_value', sa.Float(), nullable=True, comment='Quantitative signal payload where applicable (e.g. numeric rating, dwell time)'),
    sa.Column('source', sa.String(length=100), nullable=True, comment="Telemetry context/surface (e.g. 'discover_hero', 'search_result', 'movie_detail')"),
    sa.Column('event_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='Bounded metadata payload for event context'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("event_type IN ('impression', 'detail_view', 'click', 'rating')", name='chk_user_movie_event_type'),
    sa.CheckConstraint('user_id IS NOT NULL OR session_id IS NOT NULL', name='chk_user_movie_event_actor'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['user_session.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ume_movie_created', 'user_movie_event', ['movie_id', 'created_at'], unique=False)
    op.create_index('idx_ume_session_created', 'user_movie_event', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_ume_user_created', 'user_movie_event', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_ume_user_event_created', 'user_movie_event', ['user_id', 'event_type', 'created_at'], unique=False)
    op.create_index('idx_ume_user_movie', 'user_movie_event', ['user_id', 'movie_id'], unique=False)
    op.create_index(op.f('ix_user_movie_event_event_type'), 'user_movie_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_movie_event_movie_id'), 'user_movie_event', ['movie_id'], unique=False)
    op.create_index(op.f('ix_user_movie_event_session_id'), 'user_movie_event', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_movie_event_user_id'), 'user_movie_event', ['user_id'], unique=False)
    op.create_table('user_preference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True, comment='Associated user ID, or NULL for anonymous guest discovery'),
    sa.Column('session_id', sa.Uuid(), nullable=True, comment='Associated session ID from Step 16'),
    sa.Column('taxonomy_node_id', sa.BigInteger(), nullable=False, comment='Referenced canonical taxonomy node'),
    sa.Column('preference_value', sa.Float(), nullable=False, comment='Affinity weight bounded between -1.0 (aversion) and 1.0 (strong affinity)'),
    sa.Column('source', sa.String(length=50), nullable=False, comment="Origin: 'explicit', 'taste_discovery', 'derived'"),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('preference_value >= -1.0 AND preference_value <= 1.0', name='chk_user_pref_bounds'),
    sa.CheckConstraint('user_id IS NOT NULL OR session_id IS NOT NULL', name='chk_user_pref_owner'),
    sa.ForeignKeyConstraint(['session_id'], ['user_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taxonomy_node_id'], ['taxonomy_node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_pref_node_user', 'user_preference', ['taxonomy_node_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_user_preference_session_id'), 'user_preference', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_preference_taxonomy_node_id'), 'user_preference', ['taxonomy_node_id'], unique=False)
    op.create_index(op.f('ix_user_preference_user_id'), 'user_preference', ['user_id'], unique=False)
    op.create_index('uq_user_preference_session_taxonomy', 'user_preference', ['session_id', 'taxonomy_node_id'], unique=True, postgresql_where=sa.text('session_id IS NOT NULL'))
    op.create_index('uq_user_preference_user_taxonomy', 'user_preference', ['user_id', 'taxonomy_node_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('watchlist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True, comment='Owner authenticated user ID, or NULL for guest session'),
    sa.Column('session_id', sa.Uuid(), nullable=True, comment='Owner guest session ID'),
    sa.Column('movie_id', sa.Uuid(), nullable=False, comment='Canonical movie identity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('user_id IS NOT NULL OR session_id IS NOT NULL', name='chk_watchlist_owner'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['user_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_watchlist_session_created', 'watchlist', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_watchlist_user_created', 'watchlist', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_watchlist_movie_id'), 'watchlist', ['movie_id'], unique=False)
    op.create_index(op.f('ix_watchlist_session_id'), 'watchlist', ['session_id'], unique=False)
    op.create_index(op.f('ix_watchlist_user_id'), 'watchlist', ['user_id'], unique=False)
    op.create_index('uq_watchlist_session_movie', 'watchlist', ['session_id', 'movie_id'], unique=True, postgresql_where=sa.text('session_id IS NOT NULL'))
    op.create_index('uq_watchlist_user_movie', 'watchlist', ['user_id', 'movie_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_watchlist_user_movie', table_name='watchlist', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_watchlist_session_movie', table_name='watchlist', postgresql_where=sa.text('session_id IS NOT NULL'))
    op.drop_index(op.f('ix_watchlist_user_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_session_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_movie_id'), table_name='watchlist')
    op.drop_index('idx_watchlist_user_created', table_name='watchlist')
    op.drop_index('idx_watchlist_session_created', table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index('uq_user_preference_user_taxonomy', table_name='user_preference', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_user_preference_session_taxonomy', table_name='user_preference', postgresql_where=sa.text('session_id IS NOT NULL'))
    op.drop_index(op.f('ix_user_preference_user_id'), table_name='user_preference')
    op.drop_index(op.f('ix_user_preference_taxonomy_node_id'), table_name='user_preference')
    op.drop_index(op.f('ix_user_preference_session_id'), table_name='user_preference')
    op.drop_index('idx_user_pref_node_user', table_name='user_preference')
    op.drop_table('user_preference')
    op.drop_index(op.f('ix_user_movie_event_user_id'), table_name='user_movie_event')
    op.drop_index(op.f('ix_user_movie_event_session_id'), table_name='user_movie_event')
    op.drop_index(op.f('ix_user_movie_event_movie_id'), table_name='user_movie_event')
    op.drop_index(op.f('ix_user_movie_event_event_type'), table_name='user_movie_event')
    op.drop_index('idx_ume_user_movie', table_name='user_movie_event')
    op.drop_index('idx_ume_user_event_created', table_name='user_movie_event')
    op.drop_index('idx_ume_user_created', table_name='user_movie_event')
    op.drop_index('idx_ume_session_created', table_name='user_movie_event')
    op.drop_index('idx_ume_movie_created', table_name='user_movie_event')
    op.drop_table('user_movie_event')
    op.drop_index(op.f('ix_movie_rating_user_id'), table_name='movie_rating')
    op.drop_index(op.f('ix_movie_rating_movie_id'), table_name='movie_rating')
    op.drop_index('idx_movie_rating_movie_rating', table_name='movie_rating')
    op.drop_table('movie_rating')
    op.drop_index('uq_favourite_user_movie', table_name='favourite', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_favourite_session_movie', table_name='favourite', postgresql_where=sa.text('session_id IS NOT NULL'))
    op.drop_index(op.f('ix_favourite_user_id'), table_name='favourite')
    op.drop_index(op.f('ix_favourite_session_id'), table_name='favourite')
    op.drop_index(op.f('ix_favourite_movie_id'), table_name='favourite')
    op.drop_index('idx_favourite_user_created', table_name='favourite')
    op.drop_index('idx_favourite_session_created', table_name='favourite')
    op.drop_table('favourite')
    # ### end Alembic commands ###
