"""create_canonical_movie_catalog_tables

Revision ID: 1276cdf667d3
Revises: 89a21758d887
Create Date: 2026-10-03 02:21:48.057865

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1276cdf667d3'
down_revision: Union[str, None] = '89a21758d887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_collection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True, comment='Provider collection ID (e.g. TMDB collection ID)'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_collection_external_id'), 'movie_collection', ['external_id'], unique=False)
    op.create_table('taxonomy_node',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('axis', sa.String(length=50), nullable=False, comment="'genre', 'theme', 'mood', 'style'"),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_rankable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxonomy_node_axis'), 'taxonomy_node', ['axis'], unique=False)
    op.create_index(op.f('ix_taxonomy_node_key'), 'taxonomy_node', ['key'], unique=True)

    # Seed canonical taxonomy nodes directly from Veya Luma controlled vocabularies
    from datetime import datetime, timezone

    from app.domain.movie.taxonomy import get_canonical_taxonomy_seeds

    taxonomy_node_table = sa.table(
        'taxonomy_node',
        sa.column('key', sa.String),
        sa.column('label', sa.String),
        sa.column('axis', sa.String),
        sa.column('definition', sa.Text),
        sa.column('is_active', sa.Boolean),
        sa.column('is_rankable', sa.Boolean),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime),
    )
    seeds = get_canonical_taxonomy_seeds()
    now = datetime.now(timezone.utc)
    for seed in seeds:
        seed['created_at'] = now
        seed['updated_at'] = now
    op.bulk_insert(taxonomy_node_table, seeds)
    op.create_table('movie',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=False),
    sa.Column('spoken_languages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('release_year', sa.SmallInteger(), nullable=True),
    sa.Column('runtime_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='Freeform / non-taxonomy tags where justified'),
    sa.Column('collection_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(original_language) >= 2', name='chk_movie_language_length'),
    sa.CheckConstraint('release_year IS NULL OR (release_year >= 1880 AND release_year <= 2100)', name='chk_movie_release_year_range'),
    sa.CheckConstraint('runtime_minutes IS NULL OR runtime_minutes > 0', name='chk_movie_runtime_positive'),
    sa.ForeignKeyConstraint(['collection_id'], ['movie_collection.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_collection_id'), 'movie', ['collection_id'], unique=False)
    op.create_index(op.f('ix_movie_original_language'), 'movie', ['original_language'], unique=False)
    op.create_index(op.f('ix_movie_release_date'), 'movie', ['release_date'], unique=False)
    op.create_index(op.f('ix_movie_release_year'), 'movie', ['release_year'], unique=False)
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=False)
    op.create_table('movie_artwork',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('backdrop_path', sa.String(length=500), nullable=True),
    sa.Column('poster_url', sa.String(length=1000), nullable=True),
    sa.Column('backdrop_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_artwork_movie_id'), 'movie_artwork', ['movie_id'], unique=True)
    op.create_table('movie_credit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('credit_type', sa.String(length=20), nullable=False, comment="'cast' or 'crew'"),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role_or_character', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('job', sa.String(length=100), nullable=True),
    sa.Column('billing_order', sa.Integer(), nullable=True),
    sa.Column('person_external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movie_credit_lookup', 'movie_credit', ['movie_id', 'job'], unique=False)
    op.create_index('idx_movie_credit_movie_type', 'movie_credit', ['movie_id', 'credit_type'], unique=False)
    op.create_index(op.f('ix_movie_credit_job'), 'movie_credit', ['job'], unique=False)
    op.create_index(op.f('ix_movie_credit_movie_id'), 'movie_credit', ['movie_id'], unique=False)
    op.create_index(op.f('ix_movie_credit_name'), 'movie_credit', ['name'], unique=False)
    op.create_table('movie_provenance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('endpoint_or_product', sa.String(length=100), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('license_profile', sa.String(length=100), nullable=False),
    sa.Column('raw_sha256', sa.String(length=64), nullable=True),
    sa.Column('field_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='Field-level origin tracking (source_derived vs veya_derived)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_provenance_movie_id'), 'movie_provenance', ['movie_id'], unique=True)
    op.create_table('movie_tag',
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('assertion', sa.String(length=20), nullable=False, comment="'present', 'absent', 'unknown'"),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('is_curated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['taxonomy_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'node_id')
    )
    op.create_index('idx_movie_tag_movie_id', 'movie_tag', ['movie_id'], unique=False)
    op.create_index('idx_movie_tag_node_id', 'movie_tag', ['node_id'], unique=False)
    op.create_table('source_identity',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False, comment='Provider name (e.g. tmdb, imdb, wikidata)'),
    sa.Column('external_id', sa.String(length=100), nullable=False, comment='Provider-scoped external ID'),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_identity_source_external_id')
    )
    op.create_index('idx_source_identity_movie_source', 'source_identity', ['movie_id', 'source'], unique=False)
    op.create_index(op.f('ix_source_identity_movie_id'), 'source_identity', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_identity_movie_id'), table_name='source_identity')
    op.drop_index('idx_source_identity_movie_source', table_name='source_identity')
    op.drop_table('source_identity')
    op.drop_index('idx_movie_tag_node_id', table_name='movie_tag')
    op.drop_index('idx_movie_tag_movie_id', table_name='movie_tag')
    op.drop_table('movie_tag')
    op.drop_index(op.f('ix_movie_provenance_movie_id'), table_name='movie_provenance')
    op.drop_table('movie_provenance')
    op.drop_index(op.f('ix_movie_credit_name'), table_name='movie_credit')
    op.drop_index(op.f('ix_movie_credit_movie_id'), table_name='movie_credit')
    op.drop_index(op.f('ix_movie_credit_job'), table_name='movie_credit')
    op.drop_index('idx_movie_credit_movie_type', table_name='movie_credit')
    op.drop_index('idx_movie_credit_lookup', table_name='movie_credit')
    op.drop_table('movie_credit')
    op.drop_index(op.f('ix_movie_artwork_movie_id'), table_name='movie_artwork')
    op.drop_table('movie_artwork')
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_index(op.f('ix_movie_release_year'), table_name='movie')
    op.drop_index(op.f('ix_movie_release_date'), table_name='movie')
    op.drop_index(op.f('ix_movie_original_language'), table_name='movie')
    op.drop_index(op.f('ix_movie_collection_id'), table_name='movie')
    op.drop_table('movie')
    op.drop_index(op.f('ix_taxonomy_node_key'), table_name='taxonomy_node')
    op.drop_index(op.f('ix_taxonomy_node_axis'), table_name='taxonomy_node')
    op.drop_table('taxonomy_node')
    op.drop_index(op.f('ix_movie_collection_external_id'), table_name='movie_collection')
    op.drop_table('movie_collection')
    # ### end Alembic commands ###
