"""create_user_and_session_tables

Revision ID: a63771906ea8
Revises: 1276cdf667d3
Create Date: 2026-10-03 19:40:42.951486

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a63771906ea8'
down_revision: Union[str, None] = '1276cdf667d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique normalized email address for authentication'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='Unique public handle/curator username'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='Editorial display name shown on profile and curation dossiers'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Argon2id password hash'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the account is active or disabled'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Whether the account email has completed verification'),
    sa.Column('locale', sa.String(length=10), nullable=False, comment='Preferred interface locale'),
    sa.Column('country_code', sa.String(length=2), nullable=False, comment='Two-letter country code for regional catalog availability'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_app_user_email'),
    sa.UniqueConstraint('username', name='uq_app_user_username')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_username'), 'app_user', ['username'], unique=True)
    op.create_table('user_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True, comment='Associated user ID, or NULL for anonymous guest sessions'),
    sa.Column('session_type', sa.String(length=20), nullable=False, comment="Session classification: 'authenticated' or 'guest'"),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True, comment='SHA-256 digest of active rotating refresh token'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Client User-Agent string captured during session creation'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address (IPv4 or IPv6)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp after which the session credential is no longer valid'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Explicit revocation timestamp (NULL if still valid)'),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when an anonymous guest session was reconciled with a registered user'),
    sa.Column('reconciled_user_id', sa.Uuid(), nullable=True, comment='Target user ID to which this guest session was reconciled'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reconciled_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_session_refresh_hash', 'user_session', ['refresh_token_hash'], unique=False)
    op.create_index('idx_user_session_user_expires', 'user_session', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_user_session_expires_at'), 'user_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_session_refresh_token_hash'), 'user_session', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_user_session_revoked_at'), 'user_session', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_user_session_user_id'), 'user_session', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_session_user_id'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_revoked_at'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_refresh_token_hash'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_expires_at'), table_name='user_session')
    op.drop_index('idx_user_session_user_expires', table_name='user_session')
    op.drop_index('idx_user_session_refresh_hash', table_name='user_session')
    op.drop_table('user_session')
    op.drop_index(op.f('ix_app_user_username'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
